export const TreeGridLayout = {
  Cfg: {
    id: "ScenarioGrid",
    // MainCol: "SKU",
    // Sorting: "1",
    // RowHeight: 50,
    // HeaderHeight: 50,
    // HideRootTree: 1,
    // StandardFilter: 2,
    Style: "standard",
    // StretchWidth: 1,
    // StrectchHeight: 1,
    // ResizeWidth: 1,
    // ResizeHeight: 1,
    CfgId: "MockGrid",
    MainCol: "SKU",
    Tree: 0,
    // Alternate: 2,
    Delete: 0,
    NumberId: 1,
    SaveSession: "0",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "350",
    ColMoving: "1",
    MainColRelative: "0",
    NoTreeLines: 1,
    Deleting: "0",
    Toolbar: "0",
    RelHeight: 1,
    StretchWidth: 1,
    StretchHeight: 1,
    ResizeWidth: 1,
    // Style: "White",
    DynamicBorder: 1,
    Filtering: 1,
    Filtered: 1,
    ShowDeleted: 0,
    AutoUpdate: 1,
    CanMove: "2",
    Sorting: 0,
    FilterLap: "1",
    // Filter: "1",
    // Filter: "1",
  },
  Cols: [
    {
      Name: "IsSelected",
      Type: "Bool",
      // RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
      Width: 60,
    },
    {
      Name: "SKU",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "UPC",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "Category",
      Type: "Html",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
      // Width: 160,
      // Ensure CanEdit is 0 to avoid editing the HTML
    },
    {
      Name: "Description",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "Supplier",
      Type: "Html",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "Customer",
      Type: "Html",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
  ],
  Def: {
    R: {
      CanEdit: "1",
    },
    Filter: {
      CanEdit: "1",
    },
  },
  Header: {
    IsSelected: "Selected",
    SKU: "SKU",
    UPC: "UPC",
    Category: "Category",
    Description: "Description",
    Supplier: "Supplier",
    Customer: "Customer",
    Align: "Left",
    FilterBtn: "Filter",
    FilterBtnButton: "Filter",
  },
  Actions: {
    OnClickSide:
      "try { var fRow = Grid.GetRowById ? Grid.GetRowById('Filter') : Grid.GetRow('Filter'); if(fRow) { if(fRow.Visible) Grid.HideRow(fRow); else Grid.ShowRow(fRow); return -1; } } catch(e) { return -1; }",
  },
  Toolbar: { Visible: 1 },
  Panel: { Visible: 0, Select: 1 },
};
