export const AggregatorDrawerLayout = {
  Cfg: {
    CfgId: "CostAggregatorGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "0",
    NoData: "0",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  Lang: {
    Text: {
      NoData: "",
    },
  },
  LeftCols: [],
  Cols: [
    {
      Name: "Aggregator Name",
      Width: "300",
      Type: "Html",
      Caption: "Freight Cost",
    },
    {
      Name: "Cost for",
      Width: "200",
      Type: "Enum",
      Caption: "Cost for",
      Enum: "|Base UOM|Qty Per Shipment",
      EnumKeys: "|Base UOM|Qty Per Shipment",
    },
    {
      Name: "Cost per unit",
      Width: "150",
      Type: "Float",
      Format: "$0.00",
      Caption: "Cost per unit",
    },
  ],
  Header: {
    "Aggregator Name": "Freight Cost",
    "Cost for": "Cost for",
    "Cost per unit": "Cost per unit",
    "Aggregator NameAlign": "Left",
    "Cost forAlign": "Left",
    "Cost per unitAlign": "Left",
  },
};
