export const AggregatorDrawerLayout = {
  Cfg: {
    CfgId: "AggregatorDrawerGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "100",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
  },
  LeftCols: [],
  Cols: [
    {
      Name: "A",
      RelWidth: "1",
      Type: "Text",
      Caption: "Item",
    },
    {
      Name: "B",
      RelWidth: "1",
      Type: "Enum",
      Caption: "Currency",
      Enum: "|United States Dollar (USD)|Euro (EUR)",
      EnumKeys: "|USD|EUR",
    },
    {
      Name: "C",
      RelWidth: "1",
      Type: "Float",
      Format: "0.00",
      Caption: "Cost",
    },
    {
      Name: "D",
      RelWidth: "1",
      Type: "Enum",
      Caption: "Cost for",
      Enum: "|Base UOM|Carton",
      EnumKeys: "|Base UOM|Carton",
    },
    {
      Name: "E",
      RelWidth: "1",
      Type: "Float",
      Format: "$0.00",
      Caption: "Cost Per Unit",
      CanEdit: "0",
      Formula: "C",
    },
    {
      Name: "F",
      Width: "70",
      Type: "Html",
      Caption: "Action",
      CanEdit: "0",
      CanSort: "0",
    },
  ],
  Header: {
    A: "Item",
    B: "Currency",
    C: "Cost",
    D: "Cost for",
    E: "Cost Per Unit",
    F: "Action",
    FAlign: "Center",
  },
  Foot: [
    {
      id: "TotalRow",
      Spanned: "1",
      A: `<div style="display:flex; align-items:center;">
                  <button onclick="window.handleAddItemFromGrid && window.handleAddItemFromGrid()" 
                    style="background: transparent; border: none; cursor: pointer; color: #3B82F6; font-weight: 500; font-size: 13px; display: flex; align-items: center; padding: 0;">
                    <span style="font-size: 18px; margin-right: 4px;">+</span> Add Item
                  </button>
                </div>`,
      AType: "Html",
      BSpan: "3",
      B: "Total",
      BAlign: "Right",
      BType: "Text",
      EType: "Float",
      EFormat: "$0.00",
      EFormula: "sum('C')",
      Calculated: "1",
      CanEdit: "0",
    },
  ],
};
