export const ComponentDrawerLayout = {
  Cfg: {
    CfgId: "ComponentAggregatorGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "0",
    NoData: "0",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  Lang: {
    Text: {
      NoData: "",
    },
  },
  LeftCols: [],
  Cols: [
    {
      Name: "A",
      RelWidth: "1",
      Type: "Text",
      Caption: "Item",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "B",
      Width: "180",
      Type: "Enum",
      Caption: "Currency",
      Enum: "|United States Dollar (USD)",
      EnumKeys: "|USD",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "C",
      Width: "110",
      Type: "Float",
      Format: "$0.00",
      Caption: "Cost",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "D",
      Width: "140",
      Type: "Enum",
      Caption: "Cost for",
      Enum: "|Base UOM|Qty Per Shipment",
      EnumKeys: "|Base UOM|Qty Per Shipment",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "E",
      Width: "120",
      Type: "Float",
      Format: "$0.00",
      Formula: "C",
      Caption: "Cost per unit",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "F",
      Width: "70",
      Type: "Html",
      Caption: "Action",
      CanEdit: "0",
      Align: "Center",
      CanSort: "0",
    },
  ],
  Header: {
    A: "Item",
    B: "Currency",
    C: "Cost",
    D: "Cost for",
    E: "Cost per unit",
    F: "Action",
  },
  // Def: {
  //   row: {
  //     CanSelect: "0",
  //   },
  // },
  Foot: [
    {
      id: "Total",
      A: `<div style="display: flex; align-items: center; justify-content: start; gap: 8px; font-weight: 500; font-size: 13px; color: #1e3a8a; height: 100%; cursor: pointer;" onclick="window.handleAddItemFromGrid && window.handleAddItemFromGrid()">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <line x1="12" y1="5" x2="12" y2="19"></line>
              <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
            Add Item
          </div>`,
      AType: "Html",
      ASpan: 4,
      ACanEdit: "0",
      BCanEdit: "0",
      CCanEdit: "0",
      DCanEdit: "0",
      DType: "Html",
      CType: "Html",
      BType: "Html",
      EFormula: "sum()",
      EType: "Float",
      EFormat: "$0.00",
      EAlign: "Left",
      ECanEdit: "0",
      FCanEdit: "0",
      FType: "Html",
      Height: 36,
    },
  ],
};
