export const ComponentDrawerLayout = {
  Cfg: {
    CfgId: "ComponentAggregatorGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "0",
    NoData: "0",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  Lang: {
    Text: {
      NoData: "",
    },
  },
  LeftCols: [],
  Cols: [
    {
      Name: "Component Name",
      RelWidth: "1",
      Type: "Text",
      Caption: "Item",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "Currency",
      Width: "180",
      Type: "Enum",
      Caption: "Currency",
      Enum: "|United States Dollar (USD)",
      EnumKeys: "|USD",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "Cost",
      Width: "110",
      Type: "Float",
      Format: "$0.00",
      Caption: "Cost",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "Cost for",
      Width: "140",
      Type: "Enum",
      Caption: "Cost for",
      Enum: "|Base UOM|Qty Per Shipment",
      EnumKeys: "|Base UOM|Qty Per Shipment",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "Cost per unit",
      Width: "120",
      Type: "Float",
      Format: "$0.00",
      Formula: "Cost",
      Caption: "Cost per unit",
      Align: "Left",
      CanSort: "0",
    },
    {
      Name: "Actions",
      Width: "70",
      Type: "Html",
      Caption: "Action",
      CanEdit: "0",
      Align: "Center",
      CanSort: "0",
      CanFocus: "0",
    },
  ],
  Header: {
    "Component Name": "Item",
    Currency: "Currency",
    Cost: "Cost",
    "Cost for": "Cost for",
    "Cost per unit": "Cost per unit",
    Actions: "Action",
  },
  // Def: {
  //   row: {
  //     CanSelect: "0",
  //   },
  // },
  Foot: [
    {
      id: "Total",
      "Component Name": `<div style="display: flex; align-items: center; justify-content: start; gap: 8px; font-weight: 500; font-size: 13px; color: #1e3a8a; height: 100%; cursor: pointer;" onclick="window.handleAddItemFromGrid && window.handleAddItemFromGrid()">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <line x1="12" y1="5" x2="12" y2="19"></line>
              <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
            Add Item
          </div>`,
      "Component NameType": "Html",
      "Component NameSpan": 4,
      "Component NameCanEdit": "0",
      CurrencyCanEdit: "0",
      CostCanEdit: "0",
      "Cost forCanEdit": "0",
      "Cost forType": "Html",
      CostType: "Html",
      CurrencyType: "Html",
      "Cost per unitFormula": "sum()",
      "Cost per unitType": "Float",
      "Cost per unitFormat": "$0.00",
      "Cost per unitAlign": "Left",
      "Cost per unitCanEdit": "0",
      ActionsCanEdit: "0",
      ActionsType: "Html",
      Height: 36,
    },
  ],
};
