export const CustomDrawerLayout = {
  Cfg: {
    CfgId: "CustomAggregatorGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "0",
    NoData: "0",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  Lang: {
    Text: {
      NoData: "",
    },
  },
  LeftCols: [],
  Cols: [
    {
      Name: "Custom input",
      Width: "250",
      Type: "Float",
      Format: "$0.00",
      Caption: "Custom input",
    },
    {
      Name: "Action",
      Width: "120",
      Type: "Html",
      Caption: "",
      CanEdit: "0",
    },
  ],
  Header: {
    "Custom input": "Custom input",
    Action: "",
    "Custom inputAlign": "Left",
    ActionAlign: "Right",
  },
};
