export const ScenarioDetailsLayout = {
  Cfg: {
    id: "Grouping",
    IdChars: "0123456789",
    NoHScroll: "1",
    NumberId: "1",
    SuppressCfg: "1",
    IdNames: "N",
    ScrollParentHorz: "Border",
    GroupMainCol: "N",
    GroupSortMain: "1",
    GroupRestoreSort: "1",
    Group: "A,B",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "350",
    ColMoving: "1",
    MainColRelative: "0",
    NoTreeLines: "1",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    DynamicBorder: "1",
    Toolbar: "0",
    Panel: "0",
  },
  LeftCols: [
    {
      Name: "N",
      Type: "Int",
      CanEdit: "1",
      Width: "80",
      GroupWidth: "1",
      Align: "Left",
    },
  ],
  Cols: [
    { Name: "A", Width: "125", Type: "Int" },
    { Name: "B", Width: "125", CaseSensitive: "0", WhiteChars: " " },
    {
      Name: "C",
      // Width: "125",
      RelWidth: 1,
      CaseSensitive: "0",
      WhiteChars: " ",
      GroupChar: "/",
    },
    {
      Name: "D",
      Width: "125",
      CaseSensitive: "0",
      WhiteChars: " ",
      MaxChars: "1,2,3,4",
    },
    { Name: "E", Width: "115", Type: "Float", CanGroup: "0", Format: "0.00" },
  ],
  Def: [
    {
      Name: "Group",
      Expanded: "1",
      GroupMainCaption: "id (grouped)",
      IgnoreIdNames: "1",
      Calculated: "1",
      CalcOrder: "NHtmlPrefix,E",
      EFormula: "sum()",
      NCanEdit: "1",
      NHtmlPrefixFormula:
        "Row.GroupCol + (Row.GroupPos!=null?(Row.GroupPos+1):'') + ' - <b style=\"color:' + ['red','blue','green','purple'][Row.Level%4] + '\">'",
      NHtmlPostfix: "</b>",
      Spanned: "1",
      ASpan: "4",
      AType: "Text",
    },
  ],
  Solid: [
    {
      Kind: "Group",
      Cells: "List,Custom",
      ListWidth: "165",
      ListCustom: "unknown",
      List: "|none|<b>A</b> (numbers)|<b>B</b> (strings)|<b>C</b> (more group levels by separator)|<b>D</b> (more group levels by length)|A+B|B+A|A+B+C+D",
      Cols: "||A|B|C|D|A,B|B,A|A,B,C,D",
    },
    {
      Kind: "Search",
      Panel: "0",
      Cells: "EMPTY,SOLE,SINGLE,WHITE,CASE,HIDE",
      EMPTYLeft: "5",
      EMPTYType: "Bool",
      EMPTYLabelRight: "Group empty",
      EMPTY: "1",
      EMPTYOnChange:
        "for(var c in Grid.Cols) Grid.Cols[c].GroupEmpty = Value ? 2 : 0; Grid.DoGrouping(Grid.Group);",
      EMPTYTip: "Groups also rows with empty values",
      SOLEType: "Bool",
      SOLELabelRight: "Single children",
      SOLE: "1",
      SOLEOnChange:
        "for(var c in Grid.Cols) Grid.Cols[c].GroupSole = Value ? 1 : 0; Grid.DoGrouping(Grid.Group);",
      SOLETip: "Groups also rows with unique value in the column",
      SINGLEType: "Bool",
      SINGLELabelRight: "Single parents",
      SINGLE: "1",
      SINGLEOnChange:
        "for(var c in Grid.Cols) Grid.Cols[c].GroupSingle = Value ? 1 : 0; Grid.DoGrouping(Grid.Group);",
      SINGLETip: "Groups also rows with unique value in the column",
      WHITEType: "Bool",
      WHITELabelRight: "Ignore whitespace",
      WHITE: "1",
      WHITEOnChange:
        "for(var c in Grid.Cols) Grid.Cols[c].WhiteChars = Value ? ' ' : ''; Grid.DoGrouping(Grid.Group);",
      WHITETip:
        "Ignores whitespace in values when comparing, here demonstrated on C column only",
      CASEType: "Bool",
      CASELabelRight: "Case insensitive",
      CASE: "1",
      CASEOnChange:
        "for(var c in Grid.Cols) Grid.Cols[c].CaseSensitive = Value ? 0 : 1; Grid.DoGrouping(Grid.Group);",
      CASETip: "Case insensitive comparing, here demonstrated on C column only",
      HIDEType: "Bool",
      HIDELabelRight: "Hide columns",
      HIDE: "1",
      HIDEOnChange:
        "Grid.ActionGroupOff(); Grid.SetWidth('N',Value?-100:100); for(var c in Grid.Cols) if(c!='E') Grid.Cols[c].CanGroup = Value ? 1 : 2; Grid.ActionGroupOn();",
      HIDETip: "Hides the columns the grid is grouped by",
    },
  ],
  Header: { N: "id" },
};
