export const ScenarioDetailsLayout = {
  Cfg: {
    CfgId: "ScenarioDetailsGrid",
    IdChars: "0123456789",
    NumberId: "1",
    MainCol: "A",
    Group: "A",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "350",
    ColMoving: "1",
    MainColRelative: "0",
    NoTreeLines: "0",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    DynamicBorder: "0",
    Toolbar: "0",
    NoHScroll: "0",
    Sorting: "0",
    Selecting: "1",
    Deleting: "0",
    SelectingSingle: "0",
  },
  // LeftCols: [
  //   {
  //     Name: "Panel",
  //     Type: "Panel",
  //     Width: "40",
  //     Select: "1",
  //     CanEdit: "1",
  //     CanMove: "0",
  //     CanResize: "0",
  //   },
  // ],
  Cols: [
    {
      Name: "A",
      RelWidth: "1",
      Type: "Text",
      Caption: "Category",
      CanSort: "0",
    },
    { Name: "B", RelWidth: "1", Type: "Text", CanSort: "0" },
    { Name: "C", RelWidth: "1", Type: "Text", CanSort: "0" },
    { Name: "D", RelWidth: "1", Type: "Text", CanSort: "0" },
    { Name: "E", RelWidth: "1", Type: "Float", Format: "0.00", CanSort: "0" },
  ],
  Def: {
    Group: {
      Expanded: "1",
      Calculated: "1",
      CalcOrder: "E",
      EFormula: "sum()",
      CanSelect: "1",
      PanelSelect: "1",
    },
    // R: {
    //   CanSelect: "0",
    //   PanelSelect: "0",
    // },
  },
  Header: {
    // PanelSelect: "1",
    // Panel: "",
    A: "A",
    B: "B",
    C: "C",
    D: "D",
    E: "E",
  },
};
