export const ScenarioDetailsLayout = {
  Cfg: {
    CfgId: "ScenarioDetailsGrid",
    IdChars: "0123456789",
    NumberId: "1",
    MainCol: "A",
    Group: "",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "350",
    ColMoving: "1",
    MainColRelative: "0",
    NoTreeLines: "0",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    DynamicBorder: "1",
    Toolbar: "0",
    NoHScroll: "0",
    Sorting: "0",
    Selecting: "2",
    SelectingCells: "1",
    Deleting: "0",
    SelectingSingle: "0",
    RelWidthType: "1",
    FocusRow: "0",
    SelectedBackground: "#FFF9C4",
    SelectClass: "1",
    Export: "2",
    ExportFormat: "XLSX",
    ExportRows: "Visible",
    ExportCols: "Visible",
    ExportAction: "download",
  },
  // LeftCols: [
  //   {
  //     Name: "Panel",
  //     Type: "Panel",
  //     Width: "40",
  //     Select: "1",
  //     CanEdit: "1",
  //     CanMove: "0",
  //     CanResize: "0",
  //   },
  // ],
  Cols: [
    { Name: "itemId", Visible: "0" },
    {
      Name: "A",
      Width: "200",
      RelWidth: "1",
      MinWidth: "150",
      Type: "Text",
      CanSort: "0",
      MenuType: "Data",
      CanResize: "1",
    },
    {
      Name: "B",
      Width: "250",
      RelWidth: "1",
      MinWidth: "200",
      Type: "Text",
      CanSort: "0",
      MenuType: "Data",
      CanResize: "1",
    },
    {
      Name: "C",
      Width: "150",
      RelWidth: "1",
      MinWidth: "120",
      Type: "Text",
      CanSort: "0",
      MenuType: "Data",
      CanResize: "1",
    },
    {
      Name: "is_published",
      Width: "100",
      MinWidth: "100",
      Type: "Html",
      CanEdit: "0",
      CanSort: "0",
      MenuType: "Status",
      Align: "Center",
    },
  ],
  Def: {
    Group: {
      Expanded: "1",
      Calculated: "1",
      CalcOrder: "E",
      EFormula: "sum()",
      CanSelect: "1",
      PanelSelect: "1",
      CanEdit: "0",
      Spanned: "1",
      ASpan: "3",
      is_publishedVisible: "1",
    },
    R: {
      CanSelect: "1",
      PanelSelect: "1",
    },
  },
  Header: {
    A: "SKU",
    B: "Description",
    C: "Category",
    is_published: "Status",
  },
};
