export const FreightDrawerLayout = {
  Cfg: {
    CfgId: "FreightDrawerGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "200",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    MenuZIndex: "1000000",
    EnumSeparator: "|",
    EnumKeysSeparator: "|",
  },
  Cols: [
    {
      Name: "Port of Origin",
      RelWidth: "1",
      Type: "Text",
      CanEdit: "1",
      Caption: "Port of Origin",
    },
    {
      Name: "Port of Destination",
      RelWidth: "1",
      Type: "Text",
      CanEdit: "0",
      Caption: "Port of Destination",
    },
    {
      Name: "Container Type",
      RelWidth: "1",
      Type: "Text",
      CanEdit: "1",
      Caption: "Container Type",
    },
    {
      Name: "Currency",
      RelWidth: "1",
      Type: "Text",
      CanEdit: "1",
      Caption: "Currency",
    },
    {
      Name: "Rate",
      RelWidth: "0.5",
      Type: "Float",
      Format: "0.00",
      Caption: "Rate",
      CanEdit: "1",
    },
    {
      Name: "Actions",
      Width: "100",
      Type: "Html",
      Caption: "Action",
      CanEdit: "0",
      CanSort: "0",
      Align: "Center",
    },
  ],
  Header: {
    "Port of Origin": "Port of Origin",
    "Port of Destination": "Port of Destination",
    "Container Type": "Container Type",
    Currency: "Currency",
    Rate: "Rate",
    Actions: "Action",
  },
};
