export const FreightDrawerLayout = {
  Cfg: {
    CfgId: "FreightDrawerGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "200",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    Toolbar: "0",
    Sorting: "1",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
  },
  Cols: [
    {
      Name: "port_of_origin",
      RelWidth: "1",
      Type: "Text",
      Caption: "Port of Origin",
    },
    {
      Name: "port_of_destination",
      RelWidth: "1",
      Type: "Text",
      Caption: "Port of Destination",
    },
    {
      Name: "container_type",
      RelWidth: "1",
      Type: "Text",
      Caption: "Container Type",
    },
    { Name: "currency", RelWidth: "1", Type: "Text", Caption: "Currency" },
    {
      Name: "rate",
      RelWidth: "0.5",
      Type: "Float",
      Format: "0.00",
      Caption: "Rate",
    },
    {
      Name: "actions",
      Width: "100",
      Type: "Html",
      Caption: "Actions",
      CanEdit: "0",
      CanSort: "0",
      Align: "Center",
    },
  ],
  Header: {
    port_of_origin: "Port of Origin",
    port_of_destination: "Port of Destination",
    container_type: "Container Type",
    currency: "Currency",
    rate: "Rate",
    actions: "Action",
    actionsAlign: "Center",
  },
};
