export const FreightDrawerLayout = {
  Cfg: {
    CfgId: "FreightDrawerGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "200",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    Toolbar: "0",
    Sorting: "1",
    Selecting: "0",
    Editing: "1",
    CanEdit: "1",
    ReadOnly: "0",
    MenuZIndex: "1000000",
    EnumKeysSeparator: "|",
    EnumSeparator: "|",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
  },
  Cols: [
    {
      Name: "A",
      RelWidth: "1",
      Type: "Text",
      CanEdit: "1",
      Caption: "Port of Origin",
    },
    {
      Name: "B",
      RelWidth: "1",
      Type: "Text",
      CanEdit: "1",
      Caption: "Port of Destination",
    },
    {
      Name: "C",
      RelWidth: "1",
      Type: "Enum",
      Button: "Enum",
      EnumEditable: "1",
      OnClick: "ShowEnum",
      CanEdit: "1",
      Caption: "Container Type",
    },
    {
      Name: "D",
      RelWidth: "1",
      Type: "Enum",
      Button: "Enum",
      EnumEditable: "1",
      OnClick: "ShowEnum",
      CanEdit: "1",
      Caption: "Currency",
    },
    {
      Name: "E",
      RelWidth: "0.5",
      Type: "Float",
      Format: "0.00",
      Caption: "Rate",
      CanEdit: "1",
    },
    {
      Name: "F",
      Width: "100",
      Type: "Html",
      Caption: "Action",
      CanEdit: "0",
      CanSort: "0",
      Align: "Center",
    },
  ],
  Header: {
    A: "Port of Origin",
    B: "Port of Destination",
    C: "Container Type",
    D: "Currency",
    E: "Rate",
    F: "Action",
  },
};
