export const MarginMarkupDrawerLayout = {
  Cfg: {
    CfgId: "MarginMarkupDrawerGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  Cols: [
    {
      Name: "A",
      Width: "150",
      Type: "Text",
      CanEdit: "1",
      EmptyValue: "Enter %",
      Caption: "Margin %",
    },
    {
      Name: "B",
      Width: "250",
      Type: "Html",
      Caption: "Scenario builder column",
    },
    {
      Name: "C",
      Width: "150",
      Type: "Float",
      Format: "$0.00",
      Caption: "Total Cost",
      CanEdit: "0",
    },
  ],
  Header: {
    A: "Margin %",
    B: "Scenario builder column",
    C: "Total Cost",
    AAlign: "Left",
    BAlign: "Left",
    CAlign: "Left",
  },
};
