export const TariffDrawerLayout = {
  Cfg: {
    CfgId: "TariffDrawerGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  LeftCols: [],
  Cols: [
    {
      Name: "A",
      Width: "150",
      Type: "Html",
      Caption: "Tariff Rate %",
    },
    {
      Name: "B",
      Width: "200",
      Type: "Html",
      Caption: "Scenario Builder Column",
    },
    {
      Name: "C",
      Width: "150",
      Type: "Enum",
      Caption: "Cost for",
      Enum: "|Base UOM|Qty Per Shipment",
      EnumKeys: "|Base UOM|Qty Per Shipment",
    },
    {
      Name: "D",
      Width: "150",
      Type: "Float",
      Format: "$0.00",
      Caption: "Cost per unit",
    },
  ],
  Header: {
    A: "Tariff Rate %",
    B: "Scenario Builder Column",
    C: "Cost for",
    D: "Cost per unit",
    AAlign: "Left",
    BAlign: "Left",
    CAlign: "Left",
    DAlign: "Left",
  },
};
