export const TariffLibraryLayout = {
  Cfg: {
    CfgId: "TariffLibraryGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "200",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "1",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    Toolbar: "0",
    Sorting: "1",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
  },
  Cols: [
    {
      Name: "country_of_origin",
      RelWidth: "1",
      Type: "Text",
      Caption: "Country of Origin",
    },
    {
      Name: "country_of_destination",
      RelWidth: "1",
      Type: "Text",
      Caption: "Country of Destination",
    },
    {
      Name: "hs_code",
      RelWidth: "0.8",
      Type: "Text",
      Caption: "HS Code",
    },
    {
      Name: "rate",
      RelWidth: "0.5",
      Type: "Float",
      Format: "0.00'%'",
      Caption: "Rate %",
    },
    {
      Name: "actions",
      Width: "100",
      Type: "Html",
      Caption: "Action",
      CanEdit: "0",
      CanSort: "0",
      Align: "Center",
    },
  ],
  Header: {
    country_of_origin: "Country of Origin",
    country_of_destination: "Country of Destination",
    hs_code: "HS Code",
    rate: "Rate %",
    actions: "Action",
    actionsAlign: "Center",
  },
};
