export const TariffDrawerLayout = {
  Cfg: {
    CfgId: "TariffAggregatorGrid",
    IdChars: "0123456789",
    NumberId: "1",
    Style: "White",
    ReloadChanged: "1",
    Paging: "0",
    MaxHeight: "0",
    MinTagHeight: "0",
    ColMoving: "0",
    NoTreeLines: "1",
    DynamicBorder: "0",
    NoData: "0",
    RelHeight: "0",
    StretchWidth: "0",
    StretchHeight: "0",
    Toolbar: "0",
    Sorting: "0",
    Selecting: "0",
    Deleting: "0",
    SafeDelete: "0",
    Panel: "0",
    NoVScroll: "1",
    NoHScroll: "1",
  },
  Lang: {
    Text: {
      NoData: "",
    },
  },
  LeftCols: [],
  Cols: [
    {
      Name: "Tariff Rate %",
      Width: "150",
      Type: "Html",
      Caption: "Tariff Rate %",
    },
    {
      Name: "Scenario Builder Column",
      Width: "200",
      Type: "Html",
      Caption: "Scenario Builder Column",
    },
    {
      Name: "Cost per unit",
      Width: "150",
      Type: "Float",
      Format: "$0.00",
      Caption: "Cost per unit",
    },
  ],
  Header: {
    "Tariff Rate %": "Tariff Rate %",
    "Scenario Builder Column": "Scenario Builder Column",
    "Cost per unit": "Cost per unit",
    "Tariff Rate %Align": "Left",
    "Scenario Builder ColumnAlign": "Left",
    "Cost per unitAlign": "Left",
  },
};
