export const ItemMasterGridLayout = {
  Cfg: {
    Style: "White",
    CfgId: "ItemMasterGrid",
    MainCol: "SKU",
    Tree: "0",
    Delete: "0",
    NumberId: "1",
    SaveSession: "0",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "350",
    ColMoving: "1",
    MainColRelative: "0",
    NoTreeLines: "1",
    Deleting: "0",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    ResizeWidth: "1",
    DynamicBorder: "1",
    Filtering: "1",
    Filtered: "1",
    ShowDeleted: "0",
    AutoUpdate: "1",
    CanMove: "2",
    Sorting: "0",
    FilterLap: "1",
    Html: "1",
    Filter: "1",
    Toolbar: "0",
    Panel: "0",
  },
  Cols: [
    {
      Name: "SKU",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "UPC",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "Category",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "Description",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
  ],
  Def: {
    R: {
      CanEdit: "1",
    },
    Filter: {
      CanEdit: "1",
    },
  },
  Header: {
    SKU: "SKU",
    UPC: "UPC",
    Category: "Category",
    Description: "Description",
  },
  Head: [
    {
      id: "Filter",
      Kind: "Filter",
      Visible: 0,
    },
  ],
  Actions: {
    OnClickSide:
      "try { var fRow = Grid.GetRowById ? Grid.GetRowById('Filter') : Grid.GetRow('Filter'); if(fRow) { if(fRow.Visible) Grid.HideRow(fRow); else Grid.ShowRow(fRow); return -1; } } catch(e) { return -1; }",
  },
};
