export const ScenarioDetailsDummyData = {
  Body: [
    [
      { N: "1", A: "1", B: "One", C: "1/aaa/1", D: "AAA", E: "10" },
      { N: "2", A: "1", B: "One", C: "1/aaa/1", D: "A AA", E: "5" },
      { N: "3", A: "2", B: "one", C: "1/AAA/1", D: "aba", E: "2.5" },
      { N: "4", A: "2", B: "One", C: "1/a a a/2", D: "Abc", E: "12" },
      { N: "5", A: "1", B: "ONE", C: "1/aaa/2", D: "BBB", E: "33" },
      { N: "6", A: "1", B: "Two", C: "1/aaa", D: "BBCD", E: "50" },
      { N: "7", A: "2", B: "Two", C: "1/bbb/1", D: "BABB", E: "75.25" },
      { N: "8", A: "2", B: "Two", C: "1/Bbb/1", D: "ABBB", E: "40" },
      { N: "9", A: "1", B: "Three", C: "1/bbb/2", D: "CABA", E: "-10" },
      { N: "10", A: "1", B: "Four", C: "1/bbb/3", D: "C", E: "1.1" },
      { N: "11", A: "1", B: "F o u r", C: "1/Ccc/2", D: "ABCC", E: "12" },
      { N: "12", A: "1", B: "Four", C: "1/ccc/2", D: "CAA", E: "3.4" },
      { N: "13", A: "1", B: "Five", C: "1/ccc/3", D: "CC", E: "6.8" },
      { N: "14", A: "1", B: "Six", C: "1/ddd/1/xxx", D: "ABCD", E: "44" },
      { N: "15", A: "1", B: "Six", C: "1/ddd/1/xxx", D: "CBCA", E: "23" },
      { N: "16", A: "3", B: "Six", C: "2/aaa/1", D: "BCDA", E: "34" },
      { N: "17", A: "2", B: "Seven", C: "2/aaa/1", D: "CCCC", E: "3.4" },
      { N: "18", A: "2", B: "Seven", C: "2/aaa/2", D: "A", E: "3" },
      { N: "19", A: "4", B: "Eight", C: "2/aaa/2", D: "", E: "23" },
      { N: "20", A: "1", B: "Nine", C: "2/bbb/1", D: "AB", E: "16" },
      { N: "21", A: "2", B: "Nine", C: "2/bbb/1", D: "ABBB", E: "22" },
      { N: "22", A: "1", B: "NINE", C: "2", D: "BABC", E: "86" },
      { N: "23", A: "1", B: "Nine", C: "2", D: "ABB", E: "23.3" },
      { N: "24", A: "2", B: "NINE", C: "", D: "BAB", E: "15" },
      { N: "25", A: "1", B: "nine", C: "3/aaa/1/xxx", D: "CAA", E: "26.4" },
      { N: "26", A: "1", B: "Nine", C: "3/aaa/1", D: "CA", E: "34" },
      { N: "27", A: "3", B: "Ten", C: "3/aaa/2", D: "AC", E: "50" },
      { N: "28", A: "1", B: "TEN", C: "3/bbb/1", D: "AAA", E: "32.5" },
      { N: "29", A: "1", B: "TEN", C: "3/bbb/2", D: "ACC", E: "67" },
      { N: "30", A: "1", B: "Ten", C: "3/bbb/3", D: "BB", E: "3.5" },
      { N: "31", A: "1", B: "Ten", C: "3/bbb/3", D: "BCA", E: "23" },
      { N: "32", A: "1", B: "Ten", C: "3/bbb/3", D: "BAA", E: "56" },
      { N: "33", A: "0", B: "Zero", C: "3/bbb/3", D: "AAA", E: "4.5" },
      { N: "34", A: "0", B: "Z e r o", C: "3/ccc/1", D: "CC", E: "75" },
      { N: "35", A: "1", B: "", C: "3/ccc/1", D: "CC", E: "0" },
      { N: "36", A: "1", B: "", C: "3/ccc/2", D: "CAC", E: "-3" },
    ],
  ],
};
