export const baseGridCfg = {
  // CfgId: "MockGrid",
  // MainCol: "SKU",
  // Tree: 0,
  // // Alternate: 2,
  // Delete: 0,
  // NumberId: 1,
  // SaveSession: "0",
  // // Paging: "0",
  // MaxHeight: "1",
  // MinTagHeight: "350",
  // ColMoving: "1",
  // MainColRelative: "0",
  // NoTreeLines: 1,
  // Deleting: "0",
  // Toolbar: "0",
  // RelHeight: 1,
  // StretchWidth: 1,
  // StretchHeight: 1,
  // ResizeWidth: 1,
  // Style: "White",
  // DynamicBorder: 1,
  // Filtering: 1,
  // Filtered: 1,
  // ShowDeleted: 0,
  // AutoUpdate: 1,
  // CanMove: "2",
  // FilterLap: "1",
  // // Filter: "1",
  // Filter: "1",
  // ClearFilterOff: "0",
  // Html: 1,
  // AutoPages: 1,
  // Paging: 2,
  // AllPages: 1,

  CfgId: "MockGrid",
  MainCol: "SKU",
  Tree: 0,
  // Alternate: 2,
  Delete: 0,
  NumberId: 1,
  SaveSession: "0",
  Paging: "0",
  MaxHeight: "1",
  MinTagHeight: "350",
  ColMoving: "1",
  MainColRelative: "0",
  NoTreeLines: 1,
  Deleting: "0",
  Toolbar: "0",
  RelHeight: 1,
  StretchWidth: 1,
  StretchHeight: 1,
  ResizeWidth: 1,
  Style: "White",
  DynamicBorder: 1,
  Filtering: 1,
  Filtered: 1,
  ShowDeleted: 0,
  AutoUpdate: 1,
  CanMove: "2",
  FilterLap: "1",
  // Filter: "1",
  Filter: "1",
  ClearFilterOff: "0",
   Html: 1,
};
