export const ScenarioGridLayout = {
  Cfg: {
    Style: "White",
    CfgId: "ScenarioBuilderGrid",
    MainCol: "SKU",
    Tree: "0",
    Delete: "0",
    NumberId: "1",
    SaveSession: "0",
    Paging: "0",
    MaxHeight: "1",
    MinTagHeight: "350",
    ColMoving: "1",
    MainColRelative: "0",
    NoTreeLines: "1",
    Deleting: "0",
    RelHeight: "1",
    StretchWidth: "1",
    StretchHeight: "1",
    DynamicBorder: "1",
    Filtering: "1",
    Filtered: "1",
    ShowDeleted: "0",
    AutoUpdate: "1",
    CanMove: "2",
    SelectionMode: "1",
    Selecting: "1",
    Panel: "1",
    Toolbar: "0",
    Status: "0",
    PageBar: "0",
    Sorting: "0",
  },
  Cols: [
    {
      Name: "Label",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "Name",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    {
      Name: "createdAt",
      Type: "Text",
      RelWidth: 1,
      CanEdit: 1,
      CanFilter: 1,
    },
    // {
    //   Name: "Email",
    //   Type: "Text",
    //   RelWidth: 1,
    //   CanEdit: 1,
    //   CanFilter: 1,
    // },
    {
      Name: "Status",
      Type: "Html",
      RelWidth: 0,
      CanEdit: 0,
      CanFilter: 1,
    },
    {
      Name: "Actions",
      Type: "Html",
      RelWidth: 0,
      CanEdit: 0,
      CanFilter: 0,
    },
  ],
  Def: {
    R: {
      CanEdit: "1",
    },
    Filter: {
      CanEdit: "1",
    },
  },
  Header: {
    Label: "Scenario Name",
    Name: "Created By",
    createdAt: "Created At",
    // Email: "Email",
    Status: "Status",
    Actions: "Actions",
    FilterBtn: "Filter",
    FilterBtnButton: "Filter",
  },
  Head: [
    {
      id: "Filter",
      Kind: "Filter",
      Visible: 0,
    },
  ],
  Actions: {
    OnClickSide:
      "try { var fRow = Grid.GetRowById ? Grid.GetRowById('Filter') : Grid.GetRow('Filter'); if(fRow) { if(fRow.Visible) Grid.HideRow(fRow); else Grid.ShowRow(fRow); return -1; } } catch(e) { return -1; }",
  },
};
